### ISSUE TITLE
Tabs are gone

### ISSUE THREAD

**Issue by xZeroW** [JTosAddon/Tree-of-Savior-Addon-Manager#11]
Already deleted %appdata%

![tabs](https://user-images.githubusercontent.com/14045316/29618303-17e56610-87ee-11e7-8cb3-57c9fbc823ec.png)

**Comment by kajikum** [comment]
It will not work until Github's obstacle is fixed.
https://twitter.com/githubstatus/status/900336937193656320

**Comment by xZeroW** [comment]
Oh, ok, thanks!

**Comment by kajikum** [comment]
Fixed
https://twitter.com/githubstatus/status/900357651099303936
