### ISSUE TITLE
最新のmasterのコードでマネージャーを動かせない

### ISSUE THREAD

**Issue by kajikum** [JTosAddon/Tree-of-Savior-Addon-Manager#2]
日付表示でmoment.jsを使ってるはずだが、package.jsonなどに指定されていない。  
これを指定すると解決するはず

**Comment by NNAKAYAMA** [comment]
あーうん。saveするの忘れてたわ
あと多分xml2jsもオプション無しでインストールしたわ

**Comment by kajikum** [comment]
あれ？xml2jsも必要？
必要なら追加するけれど

**Comment by kajikum** [comment]
PR自体はマージされたので閉じる
