### ISSUE TITLE
更新の一言メモみたいな要素の希望

### ISSUE THREAD

**Issue by Toukibi** [JTosAddon/Tree-of-Savior-Addon-Manager#22]
addon.json内のdescriptionみたいな感じで更新の一言メモみたいなのを書いておいて、それを検出したらマネージャー内にも表示するように出来るといいな　と
改行に対応しているとなお嬉しいです。

**Comment by writ312** [comment]
updateinfoというkeyを用意して、それを表示させる的な？
descriptionに追記していくのは別か
ある程度使用決まったらツイッターで報告しますわ

**Comment by writ312** [comment]
記述方法
1.
```
"updateInfo" : "v1.0.1 保存ボタンが動かなかったバグの修正\nv1.0.0 公開"
```
2.
```
"updateInfo" : {
  "v1.0.1 保存ボタンが動かなかったバグの修正",
  "v1.0.0 公開"
```
3.
```
"updateInfo" : {
  "v1.0.1" : "保存ボタンが動かなかったバグの修正",
  "v1.0.0" : "公開"
```

**Comment by Toukibi** [comment]
完成形を提示せずに要望を出してすみません。
一応、個人的にはこのようなイメージのつもりで要望を出したのでした。

![image](https://user-images.githubusercontent.com/25131897/34338452-3d126972-e9ac-11e7-96b3-6f4ee915e696.png)

おのずと最新版に関するアップデート情報についての記述になるのでは？と思ったのです。  
ですので、1の書き方で十分だったのですよね。  
  
2の書き方が一番親切ですが、際限なくずらずら記述されても・・・という問題にもなりかねないですし。
という感じです。

**Comment by writ312** [comment]
1と2の併用型に決定
複数行あるときは下のほうが書いてて見やすいので

**Comment by weizlogy** [comment]
実装しました。
