### ISSUE TITLE
Addon keeps downloading forever

### ISSUE THREAD

**Issue by hiiwave** [JTosAddon/Tree-of-Savior-Addon-Manager#26]
I've used this manager for a long time. For unknown reason since last month I cannot successfully download any addon anymore.
Whenever I press the download button, the download icon keeps rotating forever and the process never completed. It does not give me any error message either.
I've tried to reinstall TreeofSavior and delete the temporary folder in AppData/Roaming. But it still does not work.
The version I'm playing is TWtos (http://tos.x2game.com.tw/). Most of my friends can still use this manager without problem.
I wonder if anyone encountered the same problem and hopefully have solved this. Thanks a lot!

**Comment by weizlogy** [comment]
This will happen if a network error occurs when downloading add-ons.
Please try the latest version with return code.

**Comment by weizlogy** [comment]
https://media.discordapp.net/attachments/343598546941116417/552814894651670528/unknown.png?width=801&height=463

Please check your Windows OS configuration that  described above.

**Comment by hiiwave** [comment]
Solved at version 3.1. Thanks.
