### ISSUE TITLE
Please update with new functionalities

### ISSUE THREAD

**Issue by MizukiBelhi** [JTosAddon/Tree-of-Savior-Addon-Manager#34]
https://github.com/MizukiBelhi/Tree-of-Savior-Addon-Manager/blob/master/scripts/services/addonretriever.service.js#L23

https://github.com/MizukiBelhi/Tree-of-Savior-Addon-Manager/blob/master/scripts/services/addonretrieverJP.service.js#L35

https://github.com/MizukiBelhi/Tree-of-Savior-Addon-Manager/blob/master/scripts/services/settings.service.js#L102

(removes need for json file and checks for addons by installed files)

https://github.com/MizukiBelhi/Tree-of-Savior-Addon-Manager/blob/master/scripts/browse/addon.directive.js#L85

(button to report broken addons)

Please see files for updated functionality

**Comment by weizlogy** [comment]
@MizukiBelhi 

I will change the issue URL for reporting from yours to JToS's.
If there are other differences, comment appropriately as necessary.

レポート機能のissue URLはJToS用に変更します.
その他差分があれば適宜コメントします.

**Comment by weizlogy** [comment]
settings.service.js

せっかく正規表現を使っているので、splitは使わず全部正規表現でいいと思います。
Like this:
```
var semregex = /\_(?<file>.+?)-(?<unicode>.+?)-(?<version>v.+?)\.ipf/i;
let regexedFile = semregex.exec(file)
let filename = regexedFile['file']
addonData[filename]["file"] = filename
...
```

fileVersionはサーバーのバージョンが入るはずなのでここで入れる必要はないと思います。
```
addonData[filesplit[0]]["fileVersion"] = semregex.exec(filen); //filesplit[2];
```

**Comment by weizlogy** [comment]
I think we also need to update related by addonBig. And addon.html (for adding openIssue trigger.

**Comment by weizlogy** [comment]
addon.directive.js

createIssueで https://github.com/MizukiBelhi/Addons/issues/new... とやっているけどGithubアカウントがないとログイン画面が表示されて登録できないのはちょっと...

**Comment by weizlogy** [comment]
@MizukiBelhi I finished merge this functionalities.
