### ISSUE TITLE
Files get deleted when I launch the game

### ISSUE THREAD

**Issue by ErudonZ** [JTosAddon/Tree-of-Savior-Addon-Manager#36]
Everytime I install a addon, everything works just fine, but when I open the game the files disappear from the Data folder, I have no idea why "/ Can you help me?

**Comment by weizlogy** [comment]
Since when have the symptoms appeared? Did it worked before?

**Comment by ErudonZ** [comment]
I havent played the game in over a year, I restarted playing last week, so it never worked for me.

**Comment by ErudonZ** [comment]
I worked around with it, setting the addons on the data folder to "read only' fix the issue, just in case it happens again in the future.
