### ISSUE TITLE
jtos not showing addons.

### ISSUE THREAD

**Issue by kitsukannabi** [JTosAddon/Tree-of-Savior-Addon-Manager#5]
welp, i don't know how exactly works, as a IToS user, can i install JToS Addons? 

I have already running your mod, all the addons from IToS are working great, but in the tab of JToS, it's not showing anything, i am doing something wrong? or it's just for JToS?

**Comment by kajikum** [comment]
@kitsukannabi Hi.

Umm. I have no idea.
Why do not you ask at [this forum](https://forum.treeofsavior.com/)?
