### ISSUE TITLE
Windows environment variable stops many addons to work

### ISSUE THREAD

**Issue by andreacc** [JTosAddon/Tree-of-Savior-Addon-Manager#9]
Just wanted to share this.

I spent hours trying to discover why some addons (like betterquest) were not working on my pc.

It turned out that these two windows environment variables (LUA_DEV and LUA_PATH) were set to a local installation of lua.exe on my windows. Probably the game uses a different version of lua and there was some conflict.

Erasing those two environment variables solved the issue.

https://i.imgur.com/7opTS0q.png

**Comment by writ312** [comment]
thank you
